<?php
    define('SITE__PATH','http://pioadmsys.rf.gd')
?><?php
    define('SITE__PATH','http://pioadmsys.rf.gd')
?><?php
    define('SITE__PATH','http://pioadmsys.rf.gd')
?><?php
    define('SITE__PATH','http://pioadmsys.rf.gd')
?>